### ISSUE TITLE
How to implement bincat on mac plz?

### ISSUE THREAD

**Issue by PhilWallace** [airbus-seclab/bincat#101]
My IDA version is 7.2. After installment the following warning occured:

WARNING:bincat.gui.pluginoptions:IDAUSR not defined, using /Users/carhacking/.idapro
WARNING:bincat.plugin:Could not find bincat binary, will not be able to run local analysis

Felt confused: what's the problem? Or is it because the plugin does not support MAC perfectly? Thanks a lot.

**Comment by trou** [comment]
You will need to build binCAT from source on macOS and make sure the `bincat` binary is in your $PATH. Please re-open if you have more issues.
