### ISSUE TITLE
Switch Dockerfile to Alpine

### ISSUE THREAD

**Issue by XVilka** [airbus-seclab/bincat#102]
It will [greatly reduce](https://github.com/alpinelinux/docker-alpine) the size of the container. Especially if you do a [multi stage build](https://docs.docker.com/develop/develop-images/multistage-build/).

**Comment by trou** [comment]
Hello,
thanks for the idea but I'll probably bring more problems (different libc, no apt for packages) than advantages, so maybe in the future but for now I'll close.

**Comment by XVilka** [comment]
There is "apk add pkgname" for packages.
