### ISSUE TITLE
INFO:bincat.plugin:CPU 'ARMB' is not supported, not loading BinCAT

### ISSUE THREAD

**Issue by bl4ckic3** [airbus-seclab/bincat#104]
Hi, 
When using bincat for an ARM v7 big endian (Cortex-R4) got an error for not supporting big endian in ARM, while it is officially mentioned that ARM v7 is supported. While Cortex-R4 Big Endian is officially part of ARMv7. 
Here is error:

`INFO:bincat.plugin:CPU 'ARMB' is not supported, not loading BinCAT`

**Comment by Lastpixl** [comment]
Hi,
I have [updated](https://github.com/airbus-seclab/bincat/commit/27d44f5bc97feaa5ba11db3f6999ef9f4294a7ec) the IDA plugin to support ARM big endian CPUs. It should be supported by BinCAT. Please keep us posted if it does not work!
Cheers

**Comment by bl4ckic3** [comment]
Solved as expected. 
I thought it is not officially supported.
