### ISSUE TITLE
Add Cutter/radare2 support 

### ISSUE THREAD

**Issue by XVilka** [airbus-seclab/bincat#106]
I noticed you have a plugin for IDA, but it is not the only one tool available.
[Radare2](https://github.com/radareorg/radare2) is a highly-portable cross-platform reverse engineering framework and a toolkit without dependencies.  It has support for analyzing binaries, disassembling code, debugging programs, attaching to remote GDB/LLDB, WinDbg servers, rich plugin system (see `r2pm`), and integration with various decompilers. For example, ghidra decompiler plugin - [r2ghidra-dec](https://github.com/radareorg/r2ghidra-dec). It is actively developed and can be easily integrated in various open source and commercial products. I believe, it will be highly beneficial to support these and provide a package for install from `r2pm`, see the package repository here: https://github.com/radareorg/radare2-pm

In case if you need to get the information from radare2 into the OCaml you can use the so called *r2pipe* mechanism that returns JSON-formed output for the radare2 commands. We maintain a [r2pipe opam package](https://opam.ocaml.org/packages/radare2/). Feel free to reach me if you have the question or suggestions for this r2pipe interface (or radare2 in general). 

![image](https://user-images.githubusercontent.com/203261/68269641-7ae24e00-0095-11ea-95f2-cebbc7246954.png)

For documentation on writing plugins for radare2 see [Scripting](https://radare.gitbooks.io/radare2book/content/scripting/intro.html) and [Plugins](https://radare.gitbooks.io/radare2book/content/plugins/intro.html) Radare2 Book chapters.

[Cutter](https://cutter.re/) is a crossplatform Qt/C++ GUI frontend to radare2:

![image](https://user-images.githubusercontent.com/203261/68269343-78332900-0094-11ea-8646-f6226cb6043f.png)

For documentation on writing plugins for Cutter see [the official tutorial](https://cutter.re/docs/plugins.html) and the [curated list](https://github.com/radareorg/cutter-plugins) of various popular plugins.

**Comment by thestr4ng3r** [comment]
Why was this closed?

**Comment by trou** [comment]
This was closed because we are aware of radare2/cutter and have no intention/resources to add such support. Also, I think @XVilka practice of spamming repositories to advocate radare2 is counter productive and annoying.

However, we will gladly welcome PRs that implement such support.
