### ISSUE TITLE
Improper escape in NpkGen

### ISSUE THREAD

**Issue by DarkaMaul** [airbus-seclab/bincat#112]
Hello,

While trying to run BinCAT on a binary with types information, the following exception occurred :
```python
   raise error, v # invalid expression
sre_constants.error: nothing to repeat
```
It is coming from npkgen when a structure has a regex special character in its name (e.g. +,*):
```python
# File "idabincat/npkgen.py", line 83, in get_header_data
search = r"(^\s*(?:typedef )?)\b%s\b" % s
```

Fixed line should be:
```python
search = r"(^\s*(?:typedef )?)\b%s\b" % re.escape(s)
```

I can do a PR if needed/easier.

**Comment by trou** [comment]
Hello,
thanks for the report, yes a PR is welcome :)
