### ISSUE TITLE
Output error with tutorial

### ISSUE THREAD

**Issue by DarkaMaul** [airbus-seclab/bincat#115]
Hello, 

Using both `master` and the last release in both the container or directly, I can't follow the tutorial to the end.

Indeed, if the analysis finishes, the `out.ini` file takes forever to be generated (e.g. probably days).
The problem (probably) comes from a "description" field that is too long and mostly empty (~180k characters)

Please find attached both the [init.txt](https://github.com/airbus-seclab/bincat/files/4792570/init.txt), the [analyzer.log](https://github.com/airbus-seclab/bincat/files/4792563/analyzer.log) and the [out.txt](https://github.com/airbus-seclab/bincat/files/4792571/out.txt) (I manually stopped the run after a few seconds to demonstrate the problem).

Ps: Note that I disabled the types generation

Thanks a lot for your help

**Comment by trou** [comment]
Hello,
thank you for the report and sorry for having taken so long to reply.

The current master branch does not have the problem anymore. So I'll close both Issue and PR for the time being and update with the relevant commit if we identify it.
