### ISSUE TITLE
Released BinCAT v1.2021 for Python 3

### ISSUE THREAD

**Issue by xxxzsx** [airbus-seclab/bincat#123]
Just replaced python files in BinCAT v1.1 release with new ones. Worked for me.

[bincat-win64-bin-v1.2021-python3.zip](https://github.com/airbus-seclab/bincat/files/6290941/bincat-win64-bin-v1.2021-python3.zip)
[bincat-linux64-bin-v1.2021-python3.zip](https://github.com/airbus-seclab/bincat/files/6290954/bincat-linux64-bin-v1.2021-python3.zip)

**Comment by k1p0d** [comment]
can these files be trusted ?
@trou

**Comment by trou** [comment]
Definitely not official builds, use at your own risk.

**Comment by xxxzsx** [comment]
> can these files be trusted ?
> @trou

No, these files just my build!
But it can be helpful!

If you don’t trust just download latest release from releases and download repository zip, then copy three folders (allow  replacing existing files) from `bincat-master/python/` into `bincat-***64-v1.1/python/`

It helped me. Or wait a few years till bincat team releases official Python 3 build!

**Comment by xxxzsx** [comment]
@trou Release it yourself btw. I just sharing helpful thing.

**Comment by xxxzsx** [comment]
@trou Release it yourself btw. Or reopen and pin this.

**Comment by k1p0d** [comment]
@xxxzsx @trou well I diffed the changes.. seems fine to me.. only py2->py3 changes
binaries are the same

Thanks @xxxzsx
