### ISSUE TITLE
Does bincat support analysis the firmware peripheral?

### ISSUE THREAD

**Issue by DerZc** [airbus-seclab/bincat#129]
I want to do taint analysis of ARM firmware, such as firmware of router. The taint source is the input get from peripheral, which is specific memory address, i.e., 0x40000000-0x50000000. Then find all the instructions that are tainted.
Can I do that analysis with bincan, and how can I do?

**Comment by DerZc** [comment]
I add 'mem[0x400FF000*8192] = |00|?0xFF' in configuration, and if set 0x40000000-0x50000000 as |00|?0xFF will need lot of memory, then set this memory as tainted. Bincat can run but throw exception '[ABORT] armv7: at 0xb494: software interrupt not implemented (swi=af00b580)'. Could please help me how can I ignore or skep this exception.

**Comment by szennou** [comment]
To taint from 0x40000000 to 0x50000000 excluded which is 268435456 byte wide,
you'll have to add **mem[0x40000000*268435456] = |00|!0xFF** (note the '**!'**)
This will _both_ initialize the memory to zero and taint it. If you want to let the memory _unitialized_ but taint it, add:
"mem[0x40000000*268435456] = |00|?0xFF!0xFF"

Note this is a lot of memory to make analysed by bincat. You should split that large chunk into pieces and make them analysed sequentially to measure their impact on the code.

**Comment by DerZc** [comment]
@szennou I got it. Thank you very much. 
Could you please teach me how to ignore the exception I mentioned.

**Comment by szennou** [comment]
Currently you can only skip an entire function. Currently thinking of  another solution to help you though

**Comment by szennou** [comment]
In the [analyzer] section, add **nop = 0xb494**
You can add a list of addresses to nop separated by commas, see _doc/init_format.md_

**Comment by szennou** [comment]
Could be due to a bincat's bug but we cannot help without the binary :-/

**Comment by szennou** [comment]
Please give us also the configuration file you're using

**Comment by szennou** [comment]
There was a bug in the plugin that generates the config file from IDA. Commit #30719af fixes this issue. You'll have to resinstall the plugin (see manual) after the checkout
Note that our coverage of the thumb instructions does not currently cover the whole set of instructions of your firmware. We'll add them in the coming days

**Comment by DerZc** [comment]
I got it, Thank you very much!
