### ISSUE TITLE
Can I taint functions?

### ISSUE THREAD

**Issue by DerZc** [airbus-seclab/bincat#131]
Hi! I have another question.
Can I taint a function that set the return value of this funtion as taint.

**Comment by szennou** [comment]
You can. In the configuration file, add a section like this
[<libname>]
* = fname(<conditions on paramters to taint the result>)** 

For instance to add a rule for memcpy:
[.dynsym]
* = memcpy(_, *, *)

will taint the return value if either the second or third argument is tainted
 
You can also override the taint and/or value of any register at any instruction 
**[overrride]
<instruction address> = reg[<rname], <mask> | mem[<address>], <mask>**

with <mask> having the _same syntax_ as for the initial state
For instance, to taint r2 at address 0x25484 you'll have:
[override]
0x25484 = reg[r2], !TAINT_ALL
