### ISSUE TITLE
two problems

### ISSUE THREAD

**Issue by cctv130** [airbus-seclab/bincat#134]
IDA 8.3 python10
1、
WARNING:bincat.plugin:Could not find bincat binary, will not be able to run local analysis
INFO:bincat.plugin:IDABinCAT ready.
INFO:bincat.gui:Launching the analyzer
INFO:bincat.plugin:Current analyzer path: C:\Users\wang\AppData\Local\Temp\tmpi2dydcnsbincat
INFO:bincat.plugin.npkgen:Generating TNPK file in C:\Users\wang\AppData\Local\Temp\tmpjpnamac9bincat-generate-header
INFO:bincat.plugin.npkgen:Calling 'gcc -P -E C:\Users\wang\AppData\Local\Temp\tmpjpnamac9bincat-generate-header\ida-generated.h'
ERROR:bincat.plugin.npkgen:Error encountered while running gcc. Is it installed in PATH?
WARNING:bincat.plugin:Could not compile header file, types from IDB will not be used for type propagation
WARNING:bincat.plugin:.no file containing type data for the file being analyzed could not be generated, continuing. The ida-generated header could be invalid.
ERROR:bincat.plugin:Analyzer error: Failed to start
INFO:bincat.plugin:---- stdout ----------------
INFO:bincat.plugin:b''
INFO:bincat.plugin:---- stderr ----------------
INFO:bincat.plugin:b''
INFO:bincat.plugin:---- logfile ---------------
INFO:bincat.plugin:====== end of logfile ======
ERROR:bincat.plugin:Could not parse result file
INFO:bincat.plugin:Analyzer started.

2、The configuration file cannot be found after the plugin is installed automatically and needs to be inserted manually
C:\Users\wang\AppData\Roaming\Hex-Rays\IDA Pro\plugins\idabincat\conf

**Comment by af-airbus** [comment]
To help you solve this issue, could you provide the version you tried to install: was it an official release or pre-release and which one? did you manually build on Windows?
From the few information I see, it seems like you installed a linux version of bincat on windows, or you manually build on windows using WSL/Ubuntu (which is not supported).

**Comment by af-airbus** [comment]
Ok, thank you for the information.
I see that the documentation may not be up to date for the IDA plugin installation :/  We will need to update it.

In the mean time, could you reinstall the BinCAT IDA plugin by following these steps:
1. unzip the release archive somewhere
2. launch IDA and then click on File > Script file and select the `install_plugin.py` in the freshly unzipped archive
3. copy the console output (for step 5)
4. relaunch IDA and test if BinCAT is properly installed and if it is not the case paste the output of the console in reply

**Comment by af-airbus** [comment]
Could you follow exactly the steps described in our previous reply, especially steps 3 and 4 please? The installation process must have emitted some errors.

**Comment by af-airbus** [comment]
Thank you for this output.
It seems everything went all right during the installation :/
Maybe could you try to empty your plugin directory `C:\Users\botao\AppData\Roaming\Hex-Rays\IDA Pro\plugins` and try to reinstall?

**Comment by af-airbus** [comment]
Do you have the following packages installed with cygwin?
* `mingw64-x86_64-gcc-g++`
* `mingw64-x86_64-gmp`

**Comment by af-airbus** [comment]
Yes

**Comment by af-airbus** [comment]
I have some difficulties to follow: do you have cygwin installed or not?

**Comment by af-airbus** [comment]
You *only* need a working `gcc` command in your path actually.

**Comment by af-airbus** [comment]
> You _only_ need a working `gcc` command in your path actually.

Could you managed to have *any* gcc in your path?

**Comment by af-airbus** [comment]
Do not know. Could we close this issue because it is not a bincat problem actually?
