### ISSUE TITLE
py slove pyqt5 for python 2.7

### ISSUE THREAD

**Issue by 276585877** [airbus-seclab/bincat#14]
import error : no module name pyqt5,

**Comment by Lastpixl** [comment]
Hello,

As per [README](https://github.com/airbus-seclab/bincat/blob/master/README.md), the BinCAT IDA plugin is only supported in IDA v6.9 or later.
Earlier versions of IDA used PySide instead of PyQt5. The BinCAT IDA plugin is not compatible with these versions.
