### ISSUE TITLE
Missing python requirements?

### ISSUE THREAD

**Issue by scottcarr** [airbus-seclab/bincat#15]
I am attempting to try the tutorial.  I'm using the docker container because that seems like the quickest way to get started.  However, my IDAPython is missing modules that the bincat plugin needs.

When I tried it with IDA's bundled python I was missing a module called `requests` which is needed to connect to the remote bincat analyzer.
 
I tried the instructions here: 
https://github.com/airbus-seclab/bincat/blob/master/doc/install_plugin.md#manual-install

but I'm still missing more packages.  When I open IDA it says: 

```
__init__.py: No module named urllib3
Traceback (most recent call last):
  File "/home/scott/ida-6.95/python/ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "/home/scott/.idapro/plugins/__init__.py", line 43, in <module>
    import urllib3
ImportError: No module named urllib3
```

I'm pretty sure that `__init__.py` is belongs to requests.  How do I install the missing package for my IDA's bundled python?

**Comment by trou** [comment]
Ah yes the instructions do not install the `urllib3` package which is a dependency of the `requests` package.

Could you try:
```
virtualenv -p $(which python2) /tmp/installrequests
. /tmp/installrequests/bin/activate
pip install requests
deactivate
cp -a /tmp/installrequests/lib/python*/site-packages/requests ~/.idapro/plugins/
cp -a /tmp/installrequests/lib/python*/site-packages/urllib3 ~/.idapro/plugins/
rm -rf /tmp/installrequests
```

This is a actually a ugly hack, but you can copy other potential missing dependencies before doing the `rm -rf`.

**Comment by scottcarr** [comment]
I tried that, but then urllib needed for packages.

Instead, I tried building the analyzer locally.

I ran into an issue.  The ocaml Makefile is looking for a file named `typedC.cmx` here: https://github.com/airbus-seclab/bincat/blob/master/ocaml/src/Makefile#L58

but I don't see that file anywhere in the repo.

In c2newspeak, there is a file like that.  But it does not appear to be installed by: https://github.com/airbus-seclab/c2newspeak/blob/master/src/newspeak.Makefile#L55

**Comment by trou** [comment]
@phil777 ?

**Comment by phil777** [comment]
Hi,
This my fault, I desynchronized master branch of c2newspeak and master branch of bincat because of this commit:
https://github.com/airbus-seclab/c2newspeak/commit/c97fd380111a49fa7baeb9e49c45238fca627492

Please try to install this version of c2newspeak before compiling bincat:
git checkout c97fd38^

Let us know if this fixed the problem.

**Comment by trou** [comment]
@scottcarr  please reopen if needed
