### ISSUE TITLE
Test installation procedures from scratch

### ISSUE THREAD

**Issue by phil777** [airbus-seclab/bincat#22]
Targets are
- Windows
- Ubuntu 
- Debian
- Arch linux
- Docker
- MacOS ?

**Comment by Lastpixl** [comment]
Tested installation on archlinux (branch v0.7rc), updated instructions in e5b9238a9a62a.

**Comment by Lastpixl** [comment]
Tested installation on ubuntu 16.04 (install+tests), archlinux (tests).
Updated instructions on branch v0.7rc.
On debian sid, I get the following error (from a clean chroot, installed with debootstrap):
```
File "/tmp/ocamlppe053e11aa190ec8148a246aca5b862af", line 1:
Error: Files /usr/lib/ocaml/ppx_tools/ppx_tools.cmxa
       and /usr/lib/ocaml/compiler-libs/ocamlcommon.cmxa
       make inconsistent assumptions over implementation Location
Makefile:123: recipe for target 'armv8A_ppx' failed
make[1]: *** [armv8A_ppx] Error 2
```
The output does not mention the file from which this temporary file was derived, and this temporary file is deleted automatically :-/

@trou could you look into it?

**Comment by trou** [comment]
It's a problem with current Debian sid (package desync). For further reference, the temporary file is probably the resulting .ml file after `armv8A_ppx` has been applied.

**Comment by trou** [comment]
Debian sid is now fixed. Windows install works.

**Comment by Lastpixl** [comment]
Dockerfile updated, fixed automated build, moved from "docker hub" to "docker cloud".
