### ISSUE TITLE
GUI Polishing

### ISSUE THREAD

**Issue by phil777** [airbus-seclab/bincat#27]
- [x] memory edition
- [ ] better hex dump
- [x] renaming some windows, widget reorganization
- [ ] alternative to line background coloring ?
- [x] rainbow tainting (ability to display all sources of taints)
- [x] easily run backward analysis
- [x] clear values/taints/types overrides
- [x] better desktop state/windows handling
- [ ] hide IL window by default
- [x] analysis can be long, allow the user to cancel
- [x] Goto next node dropdown is confusing

**Comment by trou** [comment]
> better desktop state/windows handling
this is apparently currently broken in IDA.

**Comment by trou** [comment]
Recommandation from Ilfak:


>  Analysis can be long in some cases. I'd recommend you to call show_wait_box() at the beginning (when IDA receives the results and gets busy with them) and hide_wait_box() at the end. IDA will become more responsive and the user will have the change to cancel the analysis (but for that you need to call user_cancelled() from time to time during analysis)

**Comment by trou** [comment]
We can do better, but I'm closing this for now
