### ISSUE TITLE
Allow overriding taint without overriding value. Ability to taint only 1 byte

### ISSUE THREAD

**Issue by phil777** [airbus-seclab/bincat#38]
Possible syntax:

`
[override]
0x1234 = stack[0x2000], !0xabcd ; stack[0x2004]; !|ff|
`

**Comment by trou** [comment]
Overriding taint without overriding value works in 5bca7ba

**Comment by trou** [comment]
It works as of e047f4e, but the following:
```ini
[overrides]
0x0 = mem[0x11], !|FFFF|
```
does not work (needs lots of changes)
