### ISSUE TITLE
Encoding issues between IDA/bincat plugin/ini file

### ISSUE THREAD

**Issue by CrackerCat** [airbus-seclab/bincat#52]
environment: win10 + IDA7.0
x86 can work,but armv7 is error.

error info

Using FLIRT signature: ARM library little endian
Propagating type information...
Function argument information has been propagated
The initial autoanalysis has been finished.
WARNING:bincat.gui.pluginoptions:IDAUSR not defined, using C:\Users\CKCat\AppData\Roaming\Hex-Rays\IDA Pro
Note: FormToPyQtWidget: importing 'sip' module into <module '__main__' from ''>
INFO:bincat.plugin:IDABinCAT ready.
DEBUG:bincat-cfg:Reading config from C:\Users\CKCat\AppData\Roaming\Hex-Rays\IDA Pro\idabincat\conf\default.ini
DEBUG:bincat-cfg:Reading OS config from C:\Users\CKCat\AppData\Roaming\Hex-Rays\IDA Pro\idabincat\conf\linux-armv7.ini
INFO:bincat.gui:Launching the analyzer
Traceback (most recent call last):
  File "C:/Users/CKCat/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idabincat\gui.py", line 265, in launch_analysis
    self.s.configurations[config_name] = self.s.edit_config
  File "C:/Users/CKCat/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idabincat\analyzer_conf.py", line 553, in wrap
    f(self, *args, **kwargs)
  File "C:/Users/CKCat/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idabincat\analyzer_conf.py", line 599, in __setitem__
    self._configs[name] = str(config)
  File "C:/Users/CKCat/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idabincat\analyzer_conf.py", line 407, in __str__
    self._config.write(sio)
  File "C:\python27-x64\Lib\ConfigParser.py", line 412, in write
    key = " = ".join((key, str(value).replace('\n', '\n\t')))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-13: ordinal not in range(128)

**Comment by CrackerCat** [comment]
I know the cause because i use the old remap file, but the bincat plugin seem clash with  Lighthouse plugin.
when two plugin is installed ,the ida will crash.

**Comment by CrackerCat** [comment]
1. BinCAT version : 0.7.
2. binary path have non ASCII characters.
the plugin is good ,thank you work.

**Comment by trou** [comment]
OK it's probably a pb with non ASCII chars, I'll try to fix it tomorrow.

**Comment by trou** [comment]
For reference, making this work is definitely not as easy as I initially thought:

* IDA 6 returns paths in the OS's encoding (as str)
* IDA 7 returns paths in UTF-8 (as str)
* IDA's open expects a string compatible with the current system encoding
* Python 2's `ConfigParser` only handles ASCII strings

So lots of fun things involved...

**Comment by trou** [comment]
and of course, OCaml's `Unix.openfile` on Windows fails if the path is in UTF-8 because it should use whatever stuff Windows uses.

**Comment by trou** [comment]
Should be fixed in g98cc1556
