### ISSUE TITLE
Can bincat work with IDA Pro 6.8?

### ISSUE THREAD

**Issue by freetimex** [airbus-seclab/bincat#6]
I only have IDA 6.8, can bincat work with it? or how can I do to make them work together,tks

**Comment by trou** [comment]
Unfortunately, BinCAT's IDA plugin uses the new PyQt interface introduced in IDA 6.9, not the PySide bindings of IDA 6.8.

So no, it does not work out of the box. You would need to port the plugin to PySide, which is deprecated.
