### ISSUE TITLE
Installation docs comments

### ISSUE THREAD

**Issue by gaeldelalleau** [airbus-seclab/bincat#61]
This is not really an issue per se, but in case this could be helpful to improve the docs, here are some comments on the user experience of an installation on MacOS after cloning the GitHub repo and trying to follow the installation documentation:

*Analyzer webservice*

* Tried to build the Docker image => fail because of a 404 error on a package the installer needs.
I had to change it to ```firejail_0.9.52-2_amd64.deb``` in the Dockerfile to make it work.
Shows an error ```Failed building wheel for itsdangerous``` but the installation seems to continue anyway.

* Tried ```docker run -p 5000:5000 airbusseclab/bincat``` to use the pre-built image => error as the image does not exists locally (docker did not tried to pull it automatically)
I think this might actually have been caused by the missing "latest" flag, I should have added ":master" as a tag to make it work.

* Tried to pull the image: ```docker pull airbusseclab/bincat``` did not work as advertised on Docker Hub docs because the tag "latest" does not exists.
```docker pull airbusseclab/bincat:master``` worked.

* Now ```docker run -p 5000:5000 airbusseclab/bincat:master``` works (with tag master).

*IDA Plugin*

* ```make IDAuser``` => "ImportError: No module named pybincat"
(I made it work by giving it directly the file paths instead of using the python one-liner that is supposed to guess the paths)
 
* ```pip2 install requests``` worked out of the box (apparently!)

* Launch IDA, then Ctrl-Shit-B: shows up the BinCat window. Noticed this warning in the console:
```WARNING:bincat.plugin:Could not find bincat binary, will not be able to run analysis```, used ```Edit/BinCAT/Options``` to configure the remote analyzer (after restarting IDA because I could not find the menu the first time, probably a neurological issue on my side).

* Launched the analysis and got:
 ```AnalyzerUnavailable: BinCAT server at http://localhost:5000 could not be reached```
Even though I can access this URL from a browser and get an answer from the BinCat daemon.

* A little python source-code tweaking in bcplugin.py allowed me to get a more helpful error message:
```NameError: global name 'requests' is not defined``` 
=> it seems pip2 did not do the job after all!
I realized that IDA uses ```/usr/bin/python``` instead of using the ```python``` interpreter in my PATH, which is a different version on my system.
I had to do ```sudo pip2 install requests``` which installed the requests package for the correct interpreter.

* Launched the analysis => it works but got an error :
```ERROR:bincat.plugin:Error while compiling file to tnpk on BinCAT analysis server.```
```
--- start of c2newspeak output ---
Fatal error: /tmp/tmprCvzIxbincat-generate-header/ida-generated.h:31#8: syntax error: unexpected token: D_FD3C3D52399ED0C4A355988E4BC1F0A0, rewrite your code
````

Tried on another binary (native ```/usr/bin/id```), got another error at the same step:
```
Fatal error: /tmp/tmpZQ_DJMbincat-generate-header/ida-generated.h:317#7: syntax error: unexpected token: __cdecl, rewrite your code
```

I have no idea if these are bugs or if BinCat is now correctly installed but not used correctly by me.
I'll now start reading the usage docs ;)

**Comment by trou** [comment]
Hello Gaël, thanks for the report !

I'll check some of the errors, but for your information, the errors about headers compilation will not prevent analysis to work, it only means that the header file exported from IDA will not be usable for type propagation.

**Comment by trou** [comment]
We've fixed / clarified everything (some in branch v0.9rc) except issue #62, so I'm closing this one.

**Comment by gaeldelalleau** [comment]
Thanks for the quick response!
I'm glad that my feedback was somewhat helpful.
I'm doing the tutorial right now on get_key_x86, it's working, I just noticed this right now: "Hover your mouse over addresses 0x1D50, 0x1D54, 0x1D58 in the stack, and observe the inferred types for the call to sprintf" is not showing tooltips at neither of these addresses.
I have tooltips on a string in memory in another location though.

**Comment by trou** [comment]
It could be that type information was not loaded.
You can check the log to see if `sprintf` types were known:
```
INFO:bincat.plugin:[INFO]  interpreter: | IMPORT all.sprintf                    addr=00004064         typing=YES tainting=no  stub=YES
```
if `typing` is `no` then maybe `libc.no` could not be found.

**Comment by gaeldelalleau** [comment]
Thanks! 
I'll check that.
