### ISSUE TITLE
Analyzer choosing wrong code path in ARMv7 example

### ISSUE THREAD

**Issue by RomanKeslerCB** [airbus-seclab/bincat#66]
Changing the configuration to reg[r0] = 2 (or any value below 5) should lead the execution of the analyzer at 0x9C0 RVA of get_key_armv7 to not take the branch and display the usage message, however the analyzer choosing to take the jump and making the wrong decision. In x86 it works fine. 
Seems like a general problem in the 'BGT' assembly command.

<img width="579" alt="capture" src="https://user-images.githubusercontent.com/23474424/39430912-da8afa72-4c97-11e8-9f73-aafef6b78a5a.PNG">

**Comment by phil777** [comment]
I believe this to be fixed in 5cf4a993.

Thanks for your report. Let us know if this worked.
