### ISSUE TITLE
Unsupported relocation type reloc(ARM,0x14)

### ISSUE THREAD

**Issue by fuying95** [airbus-seclab/bincat#68]
Bincat can support armv7 / arm v8 / x86. 
But when I loaded my test program which was ARM 32(ARM v7), it showed error:"INFO:bincat.plugin:[ABORT] elf: Unsupported relocation type [reloc(ARM,0x14)]". And I have also encountered errors like "EXCEPTION: Exceptions.Error("Unsupported relocation type [reloc(AARCH64,0x113)]")".

**Comment by trou** [comment]
thanks for your report. While we check the problem, if you use IDA, you can use the "remap binary" checkbox, as it produces a binary as seen in IDA, with relocs applied.

**Comment by trou** [comment]
I'll leave the issue open to track the needed change

**Comment by phil777** [comment]
As this is a test program, would you mind sharing it ?

**Comment by fuying95** [comment]
And I want to know is there an option that can let Bincat skip the function call, for example, 
instruction A
call fun
instruction B
...
Can I just analyze instruction A->instruction B?
Thank you very much!

**Comment by szennou** [comment]
Adding a skip on fun calls sounds a good idea and not difficult to implement. We will open an issue on it. Don't hesitate to watch the repository to be notified when we will push this new issue (by the end of the month ?)

**Comment by phil777** [comment]
I'm not sure how to correctly manage these relocations. They do not seem to have an influence on the analysis, so I added an `ignore_unknown_relocations` option in `[analyzer]` section in 
3addbdee72fe6bc01c2cc2410ee044340db57545.

```
[analyzer]
ignore_unknown_relocations = true
```

You can also use `--ignore-unknown-relocations` as command line argument since c57e46c68e69a989972c7579a46d08eece038cd8.

**Comment by trou** [comment]
Closing since the `--ignore-unknown-relocations` kind of solves it.
