### ISSUE TITLE
decoding issue

### ISSUE THREAD

**Issue by roptat** [airbus-seclab/bincat#72]
Hi, I think I found a bug in the x86 decoder. This is from the log file:

```
[DEBUG] mapped_mem: read 16 bytes at 0x38: [a2 2b 02 00 00 83 e0 0f c6 80 26 02 00 00 05 0f]
[TRACE] 0x38: [ (8)[0x2b] <- eax[0, 7]; ]
...
[DEBUG] mapped_mem: read 16 bytes at 0x3a: [02 00 00 83 e0 0f c6 80 26 02 00 00 05 0f be 05]
[TRACE] 0x3a: [ _bincat_tmp_59 <- (eax[0, 7] + (8)[eax]);,
```

and this is what capstone decodes:
```
0x08000038      a22b020000     mov byte [0x22b], al
0x0800003d      83e00f         and eax, 0xf
```

The actual instruction is `a2 2b 02 00 00` (5 bytes long) but bincat seems to think it's only 2 bytes long.

Attached is the file I try to analyse. The entrypoint is at 0x34.
[test.o.gz](https://github.com/airbus-seclab/bincat/files/2103043/test.o.gz)

**Comment by trou** [comment]
Fixed in master branch
