### ISSUE TITLE
C2newspeech error

### ISSUE THREAD

**Issue by Tiemichael** [airbus-seclab/bincat#73]
Hi,
I am very new to IdaPro and even more to BinCat.
When running the example from the tutorial I encounter following error: 
Fatal error: exception NpkParser.MenhirBasics.Error"

 bytes   pages size description

  1687552   206 8192 allocating memory for b-tree...
    65536     8 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...

  2015232            total memory allocated

Loading processor module C:\Program Files\IDA 7.0\procs\pc64.dll for metapc...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
Database for file 'get_key_x86' has been loaded.
IdaRef initialized
Snowman plugin v0.1.2 loaded.
  Press F3 to decompile the function under cursor, Ctrl-F3 to decompile the whole program.
  Press F3 (Ctrl-F3) again to jump to the address under cursor.
Shortcut Alt+8 is used for two actions:
  Edit/Plugins/IDA Instruction Reference
  WindowActivate8
Shortcut for "WindowActivate8" will be disabled.

Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>

INFO:bincat.plugin:Loading analysis results from idb
INFO:bincat.plugin:Storing analysis results to idb...
INFO:bincat.plugin:Analysis results have been stored idb.
Note: FormToPyQtWidget: importing 'sip' module into <module '__main__' from ''>
INFO:bincat.plugin:IDABinCAT ready.
INFO:bincat.gui:Launching the analyzer
INFO:bincat.plugin:Current analyzer path: c:\users\michael\appdata\local\temp\tmpuphl63bincat
ERROR:bincat.plugin.npkgen:Error encountered while running c2newspeak.
--- start of c2newspeak output ---
Fatal error: exception NpkParser.MenhirBasics.Error

--- end of c2newspeak output ---
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\npkgen.py", line 135, in generate_tnpk
    "pre-processed.c"], stderr=subprocess.STDOUT)
  File "C:\Python27\Lib\subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['c2newspeak', '--typed-npk', '-o', 'c:\\users\\michael\\appdata\\local\\temp\\tmpecvcddbincat-generate-header\\pre-processed.no', 'pre-processed.c']' returned non-zero exit status 2
WARNING:bincat.plugin:Could not compile header file, types from IDB will not be used for type propagation
WARNING:bincat.plugin:.no file containing type data for the file being analyzed could not be generated, continuing. The ida-generated header could be invalid.
INFO:bincat.plugin:Analyzer: starting process
INFO:bincat.plugin:Analyzer started.
INFO:bincat.plugin:Analyzer process finished
INFO:bincat.plugin:---- stdout ----------------
INFO:bincat.plugin:BinCAT v0.9

INFO:bincat.plugin:---- stderr ----------------

Any idea what is wrong?
Thanks!

**Comment by trou** [comment]
It's just that the header generated by IDA is not compilable. Nothing blocking, you can continue as is.
