### ISSUE TITLE
Issue with x86 rep instructions

### ISSUE THREAD

**Issue by hohohohohohoho** [airbus-seclab/bincat#75]
It appears that rep instructions (eg. rep movs) are treated as repe:
`| '\xf3' -> (* REP/REPE *) s.repe <- true; rep s Word.zero`
However, unlike repe, rep instructions do not depend on ZF. As a result
instructions like rep movsb (f3 a4) would terminate prematurely when ZF is 0.

**Comment by trou** [comment]
Indeed ! Thanks for spotting this, I'm looking into it.
