### ISSUE TITLE
Is it possible to get all the tainted instructions using python?

### ISSUE THREAD

**Issue by rainkin1993** [airbus-seclab/bincat#78]
I want to write a program to automatically taint a registry and get all the tainted instructions. Thus I want to know is it possible to get these info using python?

Thanks

**Comment by Lastpixl** [comment]
Hello,

Sure, that is possible.
From the IDA console, after the analysis has run, you can access the Python
representation of the CFA using the bc_state.cfa variable (
https://github.com/airbus-seclab/bincat/blob/master/python/idabincat/bcplugin.py#L548
).

The CFA object is defined in
https://github.com/airbus-seclab/bincat/blob/master/python/pybincat/cfa.py
-- object properties are documented there.
You can iterate bc_state.cfa.nodes.values(), and obtain EIP values for each
tainted values, using something like this (not tested):
```
tainted_states = [s.eip for s in bc_state.cfa.nodes.values() if s.Tainted]
```

Cheers

Le ven. 5 oct. 2018 à 20:18, rainkin1993 <notifications@github.com> a
écrit :

**Comment by trou** [comment]
Closing, reopen if you have more questions.

**Comment by rainkin1993** [comment]
@Lastpixl Sorry for the late reply. 
Very Thankful for your answer.

I want to ask is it possible to taint a certain registry like EAX and then start the analysis programmatically?

**Comment by trou** [comment]
It is not possible _directly_ but most of the needed code is available in the IDA plugin and relatively easy to split, for example you can use `analyzer_conf.py` to handle the initial configuration.
