### ISSUE TITLE
Installing with IDA on Wine

### ISSUE THREAD

**Issue by HoLyVieR** [airbus-seclab/bincat#8]
Just letting you know I figured a way to make the plugin load with the Windows version of IDA on Linux (with Wine). The issue I had at Recon turned out to be rather simple to fix. The only dependency I had to manually install was "pip". You may want to had to those steps in the installation for user using Wine.

 - Download "get-pip.py" : https://bootstrap.pypa.io/get-pip.py
 - Verify the signature of the script
 - ~/.wine/drive_c/Python27/python.exe get-pip.py

After that the Windows install script works fine.

**Comment by trou** [comment]
Thanks for the feedback, I'll add the info in the README.
You also might want to try the new release which includes a Windows binary.
