### ISSUE TITLE
[PE File] No mapped section at vaddr=0xffffffff

### ISSUE THREAD

**Issue by rainkin1993** [airbus-seclab/bincat#81]
# environment 

Win7 sp1
IDA 32 bit 7.0
binca v1.0.1
target file:  [pe file.zip](https://github.com/airbus-seclab/bincat/files/2683020/pe.file.zip)
(Note that this is a malware sample, do not run it! The decompress password is `pe file`) 

# Log

Output from IDA GUI console: [ida log.txt](https://github.com/airbus-seclab/bincat/files/2683025/ida.log.txt)

Bincat Log: [bincat log.zip](https://github.com/airbus-seclab/bincat/files/2683026/bincat.log.zip)

# problem

When bincat analyze a instruction which call socket, a function from Windows DLL wsock32.dll. The error will occur. The error is `INFO:bincat.plugin:Exceptions.Error("No mapped section at vaddr=0xffffffff")
`

**Comment by rainkin1993** [comment]
Help!

**Comment by szennou** [comment]
this problem is not related to socket but to the detection of external calls of kind jmp dword ptr. We added this detection to the commit ff5c882

**Comment by szennou** [comment]
corresponding release for windows is coming
