### ISSUE TITLE
Windows Manual installation : Errors during compilation / branch x64

### ISSUE THREAD

**Issue by m00dy-** [airbus-seclab/bincat#82]
Python2 command not found
Building python part.................................................
make[1]: Entering directory '/home/user/bincat/python'
python2 ./setup.py build
make[1]: python2: Command not found
make[1]: *** [Makefile:10: all] Error 127

python2 command is hardcoded in Makefile and python/Makefile files.

Zip command not found
zip -r bincat-win-v1.0.1-184-g077d5e8d-dirty.zip bincat-win-v1.0.1-184-g077d5e8d-dirty
make: zip: Command not found
make: *** [Makefile:96: windist] Error 127

I installed zip package in the Cygwin env.

**Comment by Lastpixl** [comment]
Fixed: Makefile allow overriding python interpreter name + windows install doc updated.
