### ISSUE TITLE
cannot start bincat plugin

### ISSUE THREAD

**Issue by cbwang505** [airbus-seclab/bincat#83]
Database for file 'notepad.exe' has been loaded.
Hex-Rays Decompiler plugin has been loaded (v7.0.0.170914)
  License: 57-BF5F-7D44-11 Jiang Ying, Personal license (1 user)
  The hotkeys are F5: decompile, Ctrl-F5: decompile all.
  Please check the Edit/Plugins menu for more informaton.
IDAPython Hex-Rays bindings initialized.
WARNING:bincat.gui.pluginoptions:IDAUSR not defined, using C:\Users\lenovo\AppData\Roaming\Hex-Rays\IDA Pro
INFO:bincat.plugin:Autostarting
INFO:bincat.plugin:IDABinCAT ready.
---[Python Editor v1.5 - (c) Storm Shadow - 2017 - Twitter @zadow28 - IDA PRO 7.0+]---

Note: FormToPyQtWidget: importing 'sip' module into <module '__main__' from ''>
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 1101, in OnCreate
    self.nextnodes_combo.currentTextChanged.connect(self.goto_next)
TypeError: connect() failed between currentTextChanged(QString) and goto_next()
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 435, in OnCreate
    self.region_select.currentTextChanged.connect(self.update_region)
TypeError: connect() failed between currentTextChanged(QString) and update_region()
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 608, in OnCreate
    self.cfg_select.currentIndexChanged.connect(self._load_config)
TypeError: decorated slot has no signature compatible with currentIndexChanged(int)

**Comment by cbwang505** [comment]
confict with python editor ida plugins

**Comment by trou** [comment]
Version 7.1 of IDA introduced [1] namespaces for IDA Python, it shoudl fix the problem.

- [1] http://www.hexblog.com/?p=1151
