### ISSUE TITLE
Source code is updated, but binary file is not updated

### ISSUE THREAD

**Issue by nihuai** [airbus-seclab/bincat#92]
Can you provide a compiled version?

**Comment by trou** [comment]
At some point yes. meanwhile you can compile using the instructions.

**Comment by Lastpixl** [comment]
Untested binaries are compiled automatically for each commit. See https://dev.azure.com/airbus-seclab/bincat/_build?definitionId=1, click the latest build, then "Artifacts", and select bincat-win-*.zip.
