### ISSUE TITLE
WARNING:bincat.plugin:Could not find bincat binary, will not be able to run local analysis

### ISSUE THREAD

**Issue by Dj-jom2x** [airbus-seclab/bincat#95]
WARNING:bincat.plugin:Could not find bincat binary, will not be able to run local analysis

**Comment by Dj-jom2x** [comment]
```C:\Program Files\IDA 7.0\plugins\idabincat\bin``` i already have it bincat.py

**Comment by Dj-jom2x** [comment]
i tried to dl the release zip same .. i had exe of bincat now inside of that path

**Comment by Lastpixl** [comment]
Hi,
I recommend following the [installation documentation](https://github.com/airbus-seclab/bincat#binary-distribution-install-recommended).
Cheers

**Comment by Dj-jom2x** [comment]
yup but the instruction is unclear when i log the path it expect that bin at 
```C:\Users\my name here\AppData\Roaming/Hex-Rays/IDA Pro\plugins\idabincat\bin```

i thought at the idas plugin xD

**Comment by Dj-jom2x** [comment]
it works now i manualy put the bin there
