### ISSUE TITLE
Which  ide can I use to browse the code?

### ISSUE THREAD

**Issue by Waterman178** [airbus-seclab/bincat#96]
I want to convert it to c language, but I don't understand the Ocaml language. Which ide do you use?I am looking for an open source project that supports forward and backward taint analysis.And it must be c or c++
![QQ截图20190824152111](https://user-images.githubusercontent.com/14991217/63634004-75bf5680-c683-11e9-89cf-3c81ca0f60bb.png)

**Comment by trou** [comment]
Hello,
BinCAT is deeply relying on OCaml for its implementation, a rewrite in C or C++ would not make sense.

**Comment by Waterman178** [comment]
> Hello,
> BinCAT is deeply relying on OCaml for its implementation, a rewrite in C or C++ would not make sense.

I want to understand its taint analysis algorithm, but I don't understand Ocaml, what should I do?

**Comment by trou** [comment]
Learn OCaml, it's not that hard.
